language: python
python:
  - "3.7"

branches:
  only:
  - master

env:
  - REPOS="kubevirt"

before_script:
  - ./checkout-gh-pages.sh

script:
  - for repo in $REPOS; do ./update-repo-releases.py $repo; done

# TODO: change this to a custom script to have control of commit msgs
deploy:
  provider: pages
  local_dir: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true

